### ISSUE TITLE
Firmware update fails at step-2 and leaves keyboard scrambled and touchpad not working

### ISSUE THREAD

**Issue by agurenko** [ayufan-rock64/pinebook-pro-keyboard-updater#13]
As mentioned [here](https://github.com/ayufan-rock64/pinebook-pro-keyboard-updater/issues/12#issuecomment-573314155) I also got my Pinebook Pro ANSI today and tried to run firmware update that failed at step-2.
 I think it's better to track this issue separately here.

**Comment by agurenko** [comment]
I've tried several reboots between attempts and kept getting same failure during step-2, however, when I've powered down the device and powered back on, then starting step-1, rebooting and running step-2 succeeded.

**Comment by oberon-manjaro** [comment]
I'm facing the same issue, with ISO keyboard in my case.
After running step 2 for the 1st time the touchpad stopped working.
Running it again several times always gives a bunch of 'device not found' errors and ends in a segfault:

```
rock@Debian-Desktop:~/pinebook-pro-keyboard-updater$ ./updater step-2 iso
Running STEP-2...
[*] Flashing touchpad firmware...
[*] Opening in touchpad mode
>>> Trying to open VID:258a PID:001f...
>>> Device not found
>>> Trying to open VID:258a PID:000d...
>>> Device not found
>>> Trying to open VID:258a PID:001f...
>>> Device not found
>>> Trying to open VID:258a PID:000d...
>>> Device not found
>>> Trying to open VID:258a PID:001f...
>>> Device not found
>>> Trying to open VID:258a PID:000d...
>>> Device not found
Segmentation fault
```

**Comment by oberon-manjaro** [comment]
```
(gdb) run step-2 iso
Starting program: /home/rock/pinebook-pro-keyboard-updater/updater step-2 iso
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
Running STEP-2...
[*] Flashing touchpad firmware...
[*] Opening in touchpad mode
[New Thread 0xf7623460 (LWP 2623)]
>>> Trying to open VID:258a PID:001f...
>>> Device not found
>>> Trying to open VID:258a PID:000d...
>>> Device not found
>>> Trying to open VID:258a PID:001f...
>>> Device not found
>>> Trying to open VID:258a PID:000d...
>>> Device not found
>>> Trying to open VID:258a PID:001f...
>>> Device not found
>>> Trying to open VID:258a PID:000d...
>>> Device not found

Thread 1 "updater" received signal SIGSEGV, Segmentation fault.
0xf7793d8c in libusb_control_transfer ()
   from /lib/arm-linux-gnueabihf/libusb-1.0.so.0
```
(gdb) run step-2 iso
Starting program: /home/rock/pinebook-pro-keyboard-updater/updater step-2 iso
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
Running STEP-2...
[*] Flashing touchpad firmware...
[*] Opening in touchpad mode
[New Thread 0xf7623460 (LWP 2623)]
>>> Trying to open VID:258a PID:001f...
>>> Device not found
>>> Trying to open VID:258a PID:000d...
>>> Device not found
>>> Trying to open VID:258a PID:001f...
>>> Device not found
>>> Trying to open VID:258a PID:000d...
>>> Device not found
>>> Trying to open VID:258a PID:001f...
>>> Device not found
>>> Trying to open VID:258a PID:000d...
>>> Device not found

Thread 1 "updater" received signal SIGSEGV, Segmentation fault.
0xf7793d8c in libusb_control_transfer ()
   from /lib/arm-linux-gnueabihf/libusb-1.0.so.0
(gdb) backtrace
#0  0xf7793d8c in libusb_control_transfer () from /lib/arm-linux-gnueabihf/libusb-1.0.so.0
#1  0xaaaac4ba in touchpad_verify (type=242, pass=226, sendcmd=0) at usb_touchpad.c:63
#2  0xaaaac528 in try_touchpad_verify (type=242, pass=226, sendcmd=0) at usb_touchpad.c:84
#3  0xaaaac5f8 in write_tp_fw (fw=0xaaad86c8 <firmware_tpfw_bin> "\230\340\a\001", fw_length=24576) at usb_touchpad.c:127
#4  0xaaaaae2c in flash_tp () at updater.c:47
#5  0xaaaaaf7c in step_2 (ansi_type=0) at updater.c:116
#6  0xaaaab0ca in main (argc=3, argv=0xfffef364) at updater.c:151
```

**Comment by dkarter** [comment]
Same here. Things were working fine before. Then keyboard got scrambled and trackpad stopped working. I was able to login with a usb keyboard and run step 2. That restored proper layout, but trackpad was still not working. Now my pinebook pro won’t even turn on anymore. I guess it’s since the power button is part of the keyboard. I hope this updated didn’t totally brick my machine 😭please help

**Comment by ayufan** [comment]
Power button is not. Is connected separately to soc

**Comment by dkarter** [comment]
Thanks @ayufan ! I'm not sure what happened but I left the machine charging overnight (despite it having plenty of juice before updating) and now it is turning back on and working fine 😅. That was scary.. but likely NOT due to the updater, but rather some other hardware issues I've experienced since getting the pinebook pro.

All functionality is restored for trackpad and keyboard! Thanks for your hard work on this!

**Comment by oberon-manjaro** [comment]
The segfault seen in my earlier comment seems to be related to this [PR](https://github.com/ayufan-rock64/pinebook-pro-keyboard-updater/pull/15).
However, I am still stuck without touchpad with the updater reliably failing.
Do you have any tip for me what else to do or at least how to return to old firmware and restore functionality of the touchpad?

**Comment by oberon-manjaro** [comment]
With @TobleMiner 's [commit](https://github.com/ayufan-rock64/pinebook-pro-keyboard-updater/pull/15/commits/55c1d129f2563e7bd433579ec91394cb13df1b46) included I was now able to successfully run the updater and touchpad is working now.

**Comment by oberon-manjaro** [comment]
For some reason the updater now finally succeeded - I have no idea why.

**Comment by Roxxers** [comment]
> For some reason the updater now finally succeeded - I have no idea why.

I got this error and it was caused by me forgetting to run the script as root using sudo

**Comment by jevin36** [comment]
I got the same error but I tried everything - ssh, tty from manjaro (emmc), debian (sdcard) no change. Slightest advice would be nice

**Comment by jevin36** [comment]
Hi @ayufan is there any way to roll back the update?

**Comment by seclorum** [comment]
I have just finished step-1 on my ANSI keyboard and it is now unusable - am I supposed to be able to plug a USB keyboard in, and be able to proceed from there?
